In [8]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import matplotlib as mpl

In [2]:
sentiment_analysis_df = pd.read_csv("./main_df_output/sentiment_analysis_df.csv")
sentiment_analysis_df_with_price = pd.read_csv('./main_df_output/sentiment_analysis_df_with_price.csv')

## data prepration

In [4]:
df_regression = sentiment_analysis_df_with_price.drop(['company_name','file_name','Close','D0'], axis = 1)
ctg_list = sentiment_analysis_df_with_price['Group'].unique().tolist()
day_list = sentiment_analysis_df_with_price.columns[8:]
print(ctg_list)
print(day_list)
df_regression.head(3)

['Motor/Personal', 'Global Commercial', 'London Market', 'LN Equity', 'US - Specialty/P&C/Reinsurance', 'European (Re)Insurers', 'Japanese & Pacific', 'Run-off', 'Life Groups & Retail Life', 'Other insurers']
Index(['D-1', 'D+1', 'D-2', 'D+2', 'D-3', 'D+3', 'D-5', 'D+5', 'D-10', 'D+10',
       'D-15', 'D+15'],
      dtype='object')

,Group,ticker,date,WA_sentiment,D-1,D+1,D-2,D+2,D-3,D+3,D-5,D+5,D-10,D+10,D-15,D+15
0,Motor/Personal,ADM.L,2011-03-02,-0.020513,-0.031030,0.013897,-0.020130,0.015106,-0.003612,-0.000604,-0.011350,-0.003021,-0.029326,-0.060423,-0.030463,-0.045317
1,Motor/Personal,ADM.L,2011-08-24,0.001994,-0.118567,-0.054693,-0.110454,-0.025868,-0.094983,-0.005913,-0.125969,0.011086,-0.031496,0.008130,-0.117417,-0.028825
2,Motor/Personal,ADM.L,2011-11-09,-0.012026,-0.256077,-0.076056,-0.247881,-0.053521,-0.251686,-0.061972,-0.234914,-0.098028,-0.276691,-0.025352,-0.275510,0.039437

In [18]:
# def calculate_percentage(df, ctg, day):
#     df_group = df[df['Group']==ctg]
#     def check_trend(sentiment_list, change_prc_list):
#         tag_list = []
#         for sentiment,change_prc in zip(sentiment_list,change_prc_list):
#             if ((sentiment >0)&(change_prc>0)):
#                 tag = 'upward'
#             elif ((sentiment <0)&(change_prc<0)):
#                 tag = 'downward'
#             else:
#                 tag = 'No'
#             tag_list.append(tag)
#         return tag_list

#     sentiment_list = df_group['WA_sentiment']
#     change_prc_list = df_group[day]
#     trend_list = Counter(check_trend(sentiment_list, change_prc_list))
#     total = trend_list['upward'] + trend_list['downward'] + trend_list['No'] 
#     correct_predict = (trend_list['upward'] + trend_list['downward'])/total

#     return (correct_predict)

# # calculate_percentage(df_regression,'Japanese & Pacific','D-1')

# # create a empthy dataframe to store the result
# df_result = pd.DataFrame(np.zeros((10,13)))
# col_name = ['category']
# col_name.extend(day_list)
# df_result.columns = col_name
# df_result['category'] = ctg_list
# df_result = df_result.set_index(['category'])
# # apply the function to each category
# for day in day_list:
#     for ctg in ctg_list:
#         df_result.at[ctg,day] = calculate_percentage(df_regression, ctg, day)
# def style(v, props=''):
#     return props if v >= 0.5 else None
# df_result = df_result.style.applymap(style, props='color:orange;')
# df_result

In [19]:
ticker = sentiment_analysis_df_with_price['ticker'].unique()
df_location = ['LSE','LSE','LSE','LSE','Brussels','XETRA','Paris',
                'Swiss','Milan','LSE','LSE','LSE','LSE','NYSE',
                'NYSE','NYSE','NYSE','NYSE','NYSE','NYSE','NYSE','NYSE','NYSE',
                'NYSE','Paris','XETRA','Swiss','XETRA','Japan',
                'Japan','Japan','ASX','NYSE','Toronto','LSE','LSE',
                'LSE','LSE','LSE','LSE','LSE','LSE','Amsterdam',
                'Johannesburg','Johannesburg','Oslo','Oslo','Milan','Amsterdam',
                'Copenhagen','Swiss','Helsinki','Copenhagen','IOB','Swiss',
                'Toronto']
df_place = pd.DataFrame(df_location)
df_place['ticker'] = ticker
# rename the column
df_place.columns = ['location', 'ticker']
df_place.head(5)

   location  ticker
0       LSE   ADM.L
1       LSE   DLG.L
2       LSE  SBRE.L
3       LSE  SAGA.L
4  Brussels  AGS.BR

In [22]:
df_place['location'].unique()

array(['LSE', 'Brussels', 'XETRA', 'Paris', 'Swiss', 'Milan', 'NYSE',
       'Japan', 'ASX', 'Toronto', 'Amsterdam', 'Johannesburg', 'Oslo',
       'Copenhagen', 'Helsinki', 'IOB'], dtype=object)

In [ ]:
x = np.array(self.stock_data.iloc[i: i + 11, j])                
(ca, cd) = pywt.dwt(x, "haar")                
cat = pywt.threshold(ca, np.std(ca), mode="soft")                
cdt = pywt.threshold(cd, np.std(cd), mode="soft")                
tx = pywt.idwt(cat, cdt, "haar")

In [21]:
pd.set_option('display.max_columns', None)
# merge sentiment_analysis_df_with_price with the df_place
merge_df = pd.merge(sentiment_analysis_df_with_price, df_place, on='ticker')
merge_df

,company_name,Group,ticker,file_name,date,WA_sentiment,Close,D0,D-1,D+1,D-2,D+2,D-3,D+3,D-5,D+5,D-10,D+10,D-15,D+15,location
0,Admiral Group,Motor/Personal,ADM.L,20110302_Admiral_Group_PLC-_Earnings_Call_2011...,2011-03-02,-0.020513,1655.000000,1655.000000,-0.031030,0.013897,-0.020130,0.015106,-0.003612,-0.000604,-0.011350,-0.003021,-0.029326,-0.060423,-0.030463,-0.045317,LSE
1,Admiral Group,Motor/Personal,ADM.L,20110824_Admiral_Group_PLC-_Earnings_Call_2011...,2011-08-24,0.001994,1353.000000,1353.000000,-0.118567,-0.054693,-0.110454,-0.025868,-0.094983,-0.005913,-0.125969,0.011086,-0.031496,0.008130,-0.117417,-0.028825,LSE
2,Admiral Group,Motor/Personal,ADM.L,20111109_Admiral_Group_PLC-_Guidance_Call_2011...,2011-11-09,-0.012026,887.500000,887.500000,-0.256077,-0.076056,-0.247881,-0.053521,-0.251686,-0.061972,-0.234914,-0.098028,-0.276691,-0.025352,-0.275510,0.039437,LSE
3,Admiral Group,Motor/Personal,ADM.L,20111109_Admiral_Group_PLC-_Guidance_Call_2011...,2011-11-09,-0.000319,887.500000,887.500000,-0.256077,-0.076056,-0.247881,-0.053521,-0.251686,-0.061972,-0.234914,-0.098028,-0.276691,-0.025352,-0.275510,0.039437,LSE
4,Admiral Group,Motor/Personal,ADM.L,20120307_Admiral_Group_PLC-_Earnings_Call_2012...,2012-03-07,-0.031913,1144.000000,1144.000000,0.100000,0.015734,0.095785,0.012238,0.080264,0.022727,0.062210,0.036713,0.103182,0.020979,0.179990,0.014860,LSE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1809,INTACT FINANCIAL-,Other insurers,IFC.TO,20201104_INTACT_FINANCIAL-_Earnings_Call_2020-...,2020-11-04,0.002050,147.750000,147.750000,0.063332,-0.018274,0.069258,-0.019425,0.073609,-0.060778,0.063179,-0.080203,0.031990,0.000203,0.026255,-0.019628,Toronto
1810,INTACT FINANCIAL-,Other insurers,IFC.TO,20210210_INTACT_FINANCIAL-_Earnings_Call_2021-...,2021-02-10,-0.009964,151.820007,151.820007,0.034267,-0.013371,0.041432,-0.016994,0.039294,-0.032275,0.050876,-0.041101,0.061678,-0.054802,0.054013,-0.033263,Toronto
1811,INTACT FINANCIAL-,Other insurers,IFC.TO,20210512_INTACT_FINANCIAL-_Earnings_Call_2021-...,2021-05-12,-0.001660,162.309998,162.309998,-0.016541,-0.011460,-0.027909,-0.011521,-0.015945,-0.015218,-0.009157,-0.027663,-0.003744,0.002403,-0.002704,0.041341,Toronto
1812,INTACT FINANCIAL-,Other insurers,IFC.TO,20210728_INTACT_FINANCIAL-_Earnings_Call_2021-...,2021-07-28,-0.005704,169.880005,169.880005,0.001828,-0.002943,0.008669,0.000706,0.007592,-0.002826,0.000294,0.000530,0.001238,0.026725,-0.010427,0.036320,Toronto
1813,INTACT FINANCIAL-,Other insurers,IFC.TO,20211110_INTACT_FINANCIAL-_Earnings_Call_2021-...,2021-11-10,-0.007471,169.869995,169.869995,0.022143,0.001295,0.027895,-0.006888,0.018711,-0.019191,0.027398,-0.006946,0.011793,-0.032083,0.011914,-0.057279,Toronto